// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CanhNamtest.Migrations
{
    [DbContext(typeof(LTQLDb))]
    partial class LTQLDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("CanhNamtest.Lophoc", b =>
                {
                    b.Property<int>("Malop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenlop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Malop");

                    b.ToTable("Lophoc");
                });

            modelBuilder.Entity("CanhNamtest.Sinhvien", b =>
                {
                    b.Property<string>("Masinhvien")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Malop")
                        .HasColumnType("INTEGER");

                    b.HasKey("Masinhvien");

                    b.ToTable("Sinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
